# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos-7.0-x86_64"
  #config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]   
  end  
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "/Users/ravips2394/blippar/chef-repo/cookbooks"
    chef.add_recipe "git_watchdog"
    #chef.version = "12.11.18"
    #chef.log_level = :debug
    chef.json = {}
  end	
end
